<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="https://au1996.github.io/interview/css/index.css" />
  </head>
  <body>
    <p>
      <a
        href="https://mengera88.github.io/2017/05/18/Promise%E5%8E%9F%E7%90%86%E8%A7%A3%E6%9E%90/"
        target="_blank"
        rel="noopener noreferrer"
        >文章链接</a
      >
    </p>
    <p>
      <a href="https://promisesaplus.com/" target="_blank" rel="noopener noreferrer"
        >Promises/A+规范</a
      >
    </p>
    <p>
      <a
        href="https://malcolmyu.github.io/malnote/2015/06/12/Promises-A-Plus/"
        target="_blank"
        rel="noopener noreferrer"
        >Promises/A+规范（中文）</a
      >
    </p>
    <script>
      function MyPromise(executor) {
        var PENDING = 'pending' // 待定
        var FULFILLED = 'fulfilled' // 已完成
        var REJECTED = 'rejected' // 已拒绝
        var state = PENDING // 状态
        var value = undefined // 返回值
        var reason = undefined // 失败时的原因
        var onFulfilledCallbacks = [] // 存储成功态的回调函数
        var onRejectedCallbacks = [] // 存储失败态的回调函数

        function resolve(newValue) {
          if (state === PENDING) {
            state = FULFILLED // 状态转为成功态
            value = newValue // 保存成功的返回值
            for (var i = 0; i < onFulfilledCallbacks.length; i++) {
              onFulfilledCallbacks[i](value) // 依次执行成功态的回调函数
            }
          }
        }

        function reject(newReason) {
          if (state === PENDING) {
            state = REJECTED // 状态转为失败态
            reason = newReason // 保存失败的原因
            for (var i = 0; i < onRejectedCallbacks.length; i++) {
              onRejectedCallbacks[i](reason) // 依次执行失败态的回调函数
            }
          }
        }

        try {
          executor(resolve, reject) // 执行传入的执行器函数
        } catch (error) {
          reject(error) // 如果执行器函数出错，将状态置为 rejected
        }

        function then(onFulfilled, onRejected) {
          return new MyPromise(function (resolve, reject) {
            if (state === FULFILLED) {
              try {
                var result = onFulfilled(value) // 执行成功态的回调函数
                resolve(result) // 将新 MyPromise 置为成功态
              } catch (error) {
                reject(error) // 如果执行成功态的回调函数时出错，将新 MyPromise 置为失败态
              }
            }
            if (state === REJECTED) {
              try {
                var result = onRejected(reason) // 执行失败态的回调函数
                resolve(result) // 将新 MyPromise 置为成功态
              } catch (error) {
                reject(error) // 如果执行失败态的回调函数时出错，将新 MyPromise 置为失败态
              }
            }
            if (state === PENDING) {
              onFulfilledCallbacks.push(function (val) {
                try {
                  if (typeof onFulfilled !== 'function') {
                    resolve(val)
                    return
                  }
                  var result = onFulfilled(val) // 执行成功态的回调函数
                  resolve(result) // 将新 MyPromise 置为成功态
                } catch (error) {
                  reject(error) // 如果执行成功态的回调函数时出错，将新 MyPromise 置为失败态
                }
              })
              onRejectedCallbacks.push(function (val) {
                try {
                  if (typeof onRejected !== 'function') {
                    resolve(val)
                    return
                  }
                  var result = onRejected(val) // 执行失败态的回调函数
                  resolve(result) // 将新 MyPromise 置为成功态
                } catch (error) {
                  reject(error) // 如果执行失败态的回调函数时出错，将新 MyPromise 置为失败态
                }
              })
            }
          })
        }

        function catchMethod(onRejected) {
          return then(null, onRejected) // 捕获失败态的回调函数
        }

        function finallyMethod(onFinally) {
          return then(
            function (val) {
              return MyPromise.resolve(onFinally()).then(function () {
                return val
              })
            },
            function (res) {
              return MyPromise.resolve(onFinally()).then(function () {
                throw res
              })
            }
          )
        }

        return {
          state: state,
          then: then,
          catch: catchMethod,
          finally: finallyMethod,
        }
      }

      MyPromise.resolve = function (value) {
        return new MyPromise(function (resolve) {
          resolve(value)
        })
      }

      MyPromise.reject = function (reason) {
        return new MyPromise(function (resolve, reject) {
          reject(reason)
        })
      }
    </script>

    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          // resolve(111)
          reject(111)
        }, 500)
      })
        .then(null, (res) => {
          console.log('Promise_result2', res)
        })
        .then((res) => {
          console.log('Promise_result3', res)
          throw Error('Promise_error')
        })
        .catch((err) => {
          console.log('Promise_catch', err)
        })
    </script>

    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve('------')
        }, 500)
      }).then((res) => {
        console.log(res)
      })
    </script>

    <script>
      new MyPromise((resolve, reject) => {
        setTimeout(() => {
          // resolve(111)
          reject(111)
        }, 500)
      })
        .then(null, (res) => {
          console.log('result2', res)
        })
        .then((res) => {
          console.log('result3', res)
          throw Error('my_error')
        })
        .catch((err) => {
          console.log('catch', err)
        })
    </script>
  </body>
</html>
